theme: jekyll-theme-minimal
title: Md Hafijur Rahman
description: PhD Candidate | Materials Scientist | Researcher

navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: Publications
    url: /publications
  - title: Contact
    url: /contact
include:
  - assets/style.css
